version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false -a "sh /opt/irisapp/server_start.sh"
    ports: 
      - 1972
      - 32792:52773
      - 53773
      - 8080:8080
    volumes:
      - ./:/irisdev/app
      - ./src:/opt/irisapp/src