    Do $SYSTEM.OBJ.Load("/opt/irisapp/Installer.cls", "ck")
    Do ##class(App.Installer).setup()
    
    zn "IRISAPP"
    Do EnableDeepSee^%SYS.cspServer("/csp/irisapp/")
    zpm "load /opt/irisapp/ -v -Dfolder=irisapp"

    zn "%SYS"
    Do ##class(Security.Users).UnExpireUserPasswords("*")
    Do ##class(Security.Services).Get("%Service_CallIn",.prop)
    set prop("Enabled")=1
    set prop("AutheEnabled")=48
    Do ##class(Security.Services).Modify("%Service_CallIn",.prop)

    halt